interface Image {
  name: string;
  type: string;
  size: string;
  base64: string;
}
export interface Post {
  createdAt?: string;
  _id?: string; //generated by mongo dynamically
  title: string;
  message: string;
  creator: string;
  tags: string[];
  image?: Image;
  likeCount: {
    type: number;
  };
}
