export interface Post {
  createdAt?: string;
  id?: string; //generated by mongo dynamically
  title: string;
  message: string;
  creator: string;
  tags: string[];
  image?: string;
  likeCount: {
    type: number;
  };
}
